- name: "cloud.network.public: Ensure state of Public IP [ {{ cloud_network_public.name }} ]"
  gce_eip:
    project_id: "{{ _cloud.provider.project }}"
    region: "{{ _cloud.provider.region }}"
    name: "{{ cloud_network_public.name }}"
    state: "{{ cloud_network_public.state | default(omit) }}"
  register: cloud_network_facts_public

- name: "cloud.network.public: Set cloud_network_facts.public[ {{ cloud_network_public.name }} ]"
  vars:
    cloud_network_facts: {}
  set_fact:
    cloud_network_facts: "{{ cloud_network_facts | combine({ 'public': { cloud_network_public.name: cloud_network_facts_public } }, recursive=True) }}"

- name: "cloud.network.public: Set _cloud_facts.network to cloud_network_facts"
  set_fact:
    _cloud_facts: "{{ _cloud_facts | combine({ 'network': cloud_network_facts }, recursive=True) }}"
