- name: "cloud_network: Combine cloud_provider in cloud_network"
  set_fact:
    cloud_network: "{{ cloud_network | combine(cloud_provider) }}"

- name: "cloud_network: Assert that cloud_network is mapping"
  assert:
    that:
      - cloud_network is mapping
    msg: The cloud_network variable must be a mapping (hash/dictionay).

- name: "cloud_network: Assert that cloud_network.region is string"
  assert:
    that:
      - cloud_network.region is string
    msg: The cloud_network.region variable must be a string.

- name: "cloud_network: Assert that cloud_network.zone is string"
  assert:
    that:
      - cloud_network.zone is string
    msg: The cloud_network.zone variable must be a string.

- name: "cloud_network: Assert that cloud_network.project is string"
  assert:
    that:
      - cloud_network.project is string
    msg: The cloud_network.project variable must be a string.

- name: "cloud_network: Assert that cloud_network.cidr is string"
  assert:
    that:
      - cloud_network.cidr is string
    msg: The cloud_network.cidr variable must be a string with valide cidr.
