- name: "cloud.compute: Process element [ instance ]"
  include_tasks: "compute/instance.yml"
  vars:
    cloud_compute_instance: "{{ cloud_compute_instance_dict.value }}"
  with_dict: "{{ _cloud.compute.instance | default({}) }}"
  loop_control:
    loop_var: cloud_compute_instance_dict
    label: "{{ cloud_compute_instance_dict.key }}"
