- name: "cloud.network: Process element [ public ]"
  include_tasks: "network/public.yml"
  vars:
    cloud_network_public: "{{ cloud_network_public_dict.value }}"
  with_dict: "{{ _cloud.network.public | default({}) }}"
  loop_control:
    loop_var: cloud_network_public_dict
    label: "{{ cloud_network_public_dict.key }}"
