- name: "cloud.network: Process element [ dns ]"
  include_tasks: "network/dns.yml"
  vars:
    cloud_network_dns: "{{ cloud_network_dns_dict.value }}"
  with_dict: "{{ _cloud.network.dns | default({}) }}"
  loop_control:
    loop_var: cloud_network_dns_dict
    label: "{{ cloud_network_dns_dict.key }}"
