- name: "cloud.network: Process element [ loadbalance ]"
  include_tasks: "network/loadbalance.yml"
  vars:
    cloud_network_loadbalance: "{{ cloud_loadbalance_dict.value }}"
  with_dict: "{{ _cloud.network.loadbalance | default({}) }}"
  loop_control:
    loop_var: cloud_loadbalance_dict
    label: "{{ cloud_loadbalance_dict.key }}"
