- name: "cloud.network: Process element [ subnet ]"
  include_tasks: "network/subnet.yml"
  vars:
    cloud_network_subnet: "{{ cloud_network_subnet_dict.value }}"
  with_dict: "{{ _cloud.network.subnet }}"
  loop_control:
    loop_var: cloud_network_subnet_dict
    label: "{{ cloud_network_subnet_dict.key }}"
