- name: "cloud_network: Sanity checks"
  include_tasks: "network/sanity.yml"

- name: "cloud_network: Process element [ public ]"
  include_tasks: "network/public.yml"
  vars:
    public: "{{ public_dict.value }}"
  with_dict: "{{ cloud_network.public }}"
  loop_control:
    loop_var: public_dict
    label: "{{ public_dict.key }}"
  when: cloud_network.public is mapping

- name: "cloud_network: Process element [ subnet ]"
  include_tasks: "network/subnet.yml"
  vars:
    cloud_network_subnet: "{{ cloud_network_subnet_dict.value }}"
  with_dict: "{{ cloud_network.subnet }}"
  loop_control:
    loop_var: cloud_network_subnet_dict
    label: "{{ cloud_network_subnet_dict.key }}"
  when: cloud_network.subnet is mapping

- name: "cloud_network: Process element [ firewall ]"
  include_tasks: "network/firewall.yml"
  vars:
    cloud_network_firewall: "{{ cloud_network_firewall_dict.value }}"
  with_dict: "{{ cloud_network.firewall | default({}) }}"
  loop_control:
    loop_var: cloud_network_firewall_dict
    label: "{{ cloud_network_firewall_dict.key }}"
  when: cloud_network.firewall is mapping

- name: "cloud_network: Process element [ loadbalance ]"
  include_tasks: "network/loadbalance.yml"
  vars:
    loadbalance: "{{ loadbalance_dict.value }}"
  with_dict: "{{ cloud_network.loadbalance | default({}) }}"
  loop_control:
    loop_var: loadbalance_dict
    label: "{{ loadbalance_dict.key }}"
  when: cloud_network.loadbalance is mapping

- name: "cloud_network: Process element [ dns ]"
  include_tasks: "network/dns.yml"
  vars:
    cloud_network_dns: "{{ cloud_network_dns_dict.value }}"
  with_dict: "{{ cloud_network.dns | default({}) }}"
  loop_control:
    loop_var: cloud_network_dns_dict
    label: "{{ cloud_network_dns_dict.key }}"
  when: cloud_network.dns is mapping
