- name: "storage.cloud_storage_bucket.action: [ mkdir ]"
  gc_storage:
    gs_access_key: "{{ lookup('ENV','GS_ACCESS_KEY_ID') | default(omit) }}"
    gs_secret_key: "{{ lookup('ENV','GS_SECRET_ACCESS_KEY') | default(omit) }}"
    region: "{{ _cloud.provider.region }}"
    bucket: "{{ cloud_storage_bucket.name }}"
    object: "{{ cloud_storage_bucket_action.mkdir }}"
    permission: "{{ cloud_storage_bucket_action.permission | default(omit) }}"
    mode: "create"
  when: cloud_storage_bucket_action.mkdir is defined

- name: "storage.cloud_storage_bucket.action: [ rm ]"
  gc_storage:
    gs_access_key: "{{ lookup('ENV','GS_ACCESS_KEY_ID') | default(omit) }}"
    gs_secret_key: "{{ lookup('ENV','GS_SECRET_ACCESS_KEY') | default(omit) }}"
    region: "{{ _cloud.provider.region }}"
    bucket: "{{ cloud_storage_bucket.name }}"
    object: "{{ cloud_storage_bucket_action.rm }}"
    mode: "delete"
  when: cloud_storage_bucket_action.rm is defined

- name: "storage.cloud_storage_bucket.action: [ cat ]"
  block:
    - name: "cat"
      gc_storage:
        gs_access_key: "{{ lookup('ENV','GS_ACCESS_KEY_ID') | default(omit) }}"
        gs_secret_key: "{{ lookup('ENV','GS_SECRET_ACCESS_KEY') | default(omit) }}"
        region: "{{ _cloud.provider.region }}"
        bucket: "{{ cloud_storage_bucket.name }}"
        object: "{{ cloud_storage_bucket_action.cat }}"
        mode: "get_str"
      register: _cloud_storage_bucket_action_cat

    - name: "register"
      vars:
        cloud_storage_bucket_action_cat: "{{ cloud_storage_bucket_action_cat | default([]) }}"
      set_fact:
        cloud_storage_bucket_action_cat: "{{ cloud_storage_bucket_action_cat + _cloud_storage_bucket_action_cat }}"
  when: cloud_storage_bucket_action.cat is defined

- name: "storage.cloud_storage_bucket.action: [ upload ]"
  gc_storage:
    gs_access_key: "{{ lookup('ENV','GS_ACCESS_KEY_ID') | default(omit) }}"
    gs_secret_key: "{{ lookup('ENV','GS_SECRET_ACCESS_KEY') | default(omit) }}"
    region: "{{ _cloud.provider.region }}"
    bucket: "{{ cloud_storage_bucket.name }}"
    object: "{{ cloud_storage_bucket_action.upload }}"
    permission: "{{ cloud_storage_bucket_action.permission | default(omit) }}"
    src: "{{ cloud_storage_bucket_action.from }}"
    mode: "put"
  when: cloud_storage_bucket_action.upload is defined

- name: "storage.cloud_storage_bucket.action: [ download ]"
  gc_storage:
    gs_access_key: "{{ lookup('ENV','GS_ACCESS_KEY_ID') | default(omit) }}"
    gs_secret_key: "{{ lookup('ENV','GS_SECRET_ACCESS_KEY') | default(omit) }}"
    region: "{{ _cloud.provider.region }}"
    bucket: "{{ cloud_storage_bucket.name }}"
    object: "{{ cloud_storage_bucket_action.download }}"
    dest: "{{ cloud_storage_bucket_action.to }}"
    mode: "get"
  when: cloud_storage_bucket_action.download is defined
